### ISSUE TITLE
v2.53.0: missing search-engine.mjs causes ERR_MODULE_NOT_FOUND (MCP server fails to start)

### ISSUE THREAD

**Issue by zackzhwu-hub** [sdsrss/claude-mem-lite#15]
### Version
claude-mem-lite v2.53.0 (latest as of 2026-04-29)

### Problem
After upgrading to v2.53.0, the MCP server fails to start with the following error:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/zack/.npm-global/lib/node_modules/claude-mem-lite/search-engine.mjs' imported from /Users/zack/.npm-global/lib/node_modules/claude-mem-lite/server.mjs'
```

### Root Cause
Both `server.mjs` (line 13) and `mem-cli.mjs` import from `./search-engine.mjs`:
```js
import { searchObservationsHybrid } from './search-engine.mjs';
```

However, this file is **not included** in the published npm package. I verified by checking the v2.53.0 tarball — `search-engine.mjs` is absent.

Note: v2.52.0 does not have this import and works correctly.

### Impact
- MCP server cannot start → all mem tools (mem_save, mem_search, mem_recall, etc.) are unavailable
- Auto-update mechanism (hook-update.mjs) keeps re-downloading v2.53.0, so the fix gets overwritten on every session start

### Workaround
Downgrade to v2.52.0 and disable auto-update:
```bash
npm install -g claude-mem-lite@2.52.0 --force
# Copy v2.52.0 server.mjs and mem-cli.mjs to ~/.claude-mem-lite/
# Add CLAUDE_MEM_SKIP_UPDATE=1 to Claude Code settings.json env to prevent auto-update
```

### Suggested Fix
Add `search-engine.mjs` to the `files` field in `package.json`, or include it in the npm publish configuration.

### Environment
- macOS Darwin 25.3.0
- Node.js v24.12.0
- Claude Code CLI

**Comment by sdsrss** [comment]
Thanks for the detailed report — investigated and have findings + a fix.

## What I verified

Pulled the v2.53.0 tarball directly from three sources:

| Source | `search-engine.mjs` | Total files |
|---|---|---|
| npm registry (`registry.npmjs.org`) | ✓ 12642 bytes | 90 |
| npmmirror (China mirror) | ✓ 12642 bytes | 90 |
| GitHub release tarball | ✓ | matches commit `ae850fe` |

So the file IS shipped in v2.53.0. Your local `~/.npm-global/lib/node_modules/claude-mem-lite/` ended up missing it for some other reason — most likely interrupted `npm install`, npm cache corruption, a permission issue, or a partial download.

Quick verify:
```bash
ls -la ~/.npm-global/lib/node_modules/claude-mem-lite/search-engine.mjs
shasum -a 256 ~/.npm-global/lib/node_modules/claude-mem-lite/server.mjs
```

Force-reinstall should fix it immediately:
```bash
npm install -g claude-mem-lite@2.53.1 --force
```

Re: *"auto-update keeps re-downloading v2.53.0, so the fix gets overwritten"* — `hook-update.mjs` actually writes to `~/.claude-mem-lite/`, **not** to `~/.npm-global/lib/node_modules/claude-mem-lite/`. So whatever fix you apply at the npm-global path shouldn't be touched by auto-update. If you're still seeing repeated overwrite, please share `npm config get registry` and any proxy/mirror config — that would help track down what's environment-specific.

## Fix shipped: v2.53.1

Even though the file is published correctly, a partial install on the user side shouldn't crash with an opaque `ERR_MODULE_NOT_FOUND` stack. v2.53.1 adds a preflight in `scripts/launch.mjs`:

1. Before importing `server.mjs`, scans its relative `.mjs` imports (static + dynamic) and checks each file exists.
2. If the primary install is incomplete, **falls back automatically** to `~/.claude-mem-lite/server.mjs` (maintained by `hook-update.mjs`, separate from `~/.npm-global/`) when that copy is healthy.
3. If both are broken, exits with a clear repair command instead of a Node stack trace.

So even with a half-broken npm-global install, the MCP server should now either work via fallback or give you an actionable error.

Closing this — please reopen if `--force` reinstall still leaves you in a broken state on v2.53.1. Would love to track down the root cause on your end.

Release: https://github.com/sdsrss/claude-mem-lite/releases/tag/v2.53.1
